# Generated by Django 3.1 on 2021-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagelink', '0006_auto_20210522_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, default='bhilai', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='skill',
            field=models.CharField(blank=True, default='Gardening', max_length=100),
        ),
    ]
